{"uuid": "618c3ec9-5402-47e4-82be-7f7ad9914b5f", "children": ["24fac7e7-752b-4309-bf52-ec6fee80cf0d"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "TypeError: exceptions must derive from BaseException\n", "trace": "  File \"E:\\python\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\python\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\python\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"H:\\PyAutoTest\\Testcases\\TestCase_shop.py\", line 14, in login\n    driver.visit(Get_Config().get_config('url', 'ui_url'))\n  File \"H:\\PyAutoTest\\Config\\config.py\", line 33, in get_config\n    raise ('文件读取错误', error)\n"}, "start": 1593618747282, "stop": 1593618752259}], "start": 1593618747282, "stop": 1593618752328}