{"uuid": "2ef212e2-6e31-4049-8e47-88062f5fe0ed", "children": ["17cd1b9c-7ec1-492e-b168-00c3f485ecb9"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "TypeError: exceptions must derive from BaseException\n", "trace": "  File \"E:\\python\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\python\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\python\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"H:\\PyAutoTest\\Testcases\\TestCase_shop.py\", line 14, in login\n    driver.visit(Get_Config().get_config('url', 'ui_url'))\n  File \"H:\\PyAutoTest\\Config\\config.py\", line 33, in get_config\n    raise ('文件读取错误', error)\n"}, "start": 1593618766827, "stop": 1593618771854}], "start": 1593618766827, "stop": 1593618771923}